Places API & Config
Bottigerd/location-app pull request #6
Opened 2023-02-08 22:31 UTC by Bottigerd

### Changes:
- API calls no longer occur on launch, but the map is center on the current location if there are location permissions
- Broke up the location authorization/permission function into multiple ones so hopefully the code is cleaner like Jeff wanted
- Places API is implemented, if reverse-geocoding returns a `place_id` in the struct, it'll call the places API and return the name of the place with the town, state, postal code, and country to the address still mimics the formatted address response of the reverse geocoding api
- Implemented `config.json` to store sensitivity information like the API key. It's in the `.gitignore` already. The config goes in `location-app/SwiftUI-UserLocation/config.json`. You can find the config in the google drive for safe-keeping

### Something I noticed and will need fixing and was present before this branch:
- the API calls run but don't necessarily save the response before the application tries to display the address. This means the button is pressed about three times before the right information is shown
- I believe this has to do with async and sync functions or completion handlers (ways to make sure other code doesn't execute until something else is done)
- I spent way too long debugging this using completion handlers and async functions but could not figure it out. Async functions don't look promising but completion handlers look a bit more promising
- This is a plea for help for someone to also take a look at this

2023-02-09 15:42 UTC, kittyTyree requested changes
The changes for a commit that got pushed that cuts down lines of code in getPlaceName() causes a compiler error when I try and run the code. Even though the formatting gets changed and, granted, looks cleaner in the code, I might suggest changing it back to what it was before the changes were made so that it does not run this compiler issue (even if the error didn't show up on your system.)

2023-02-09 15:42 UTC, kittyTyree commented on SwiftUI-UserLocation/SwiftUI-UserLocation/ContentViewModel.swift
> +        return place_name + ", " + locality + ", " + admin_area_1 + " " + postal_code + ", " + country
I am getting an error on this line: "The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions"

2023-02-09 15:42 UTC, kittyTyree commented on SwiftUI-UserLocation/SwiftUI-UserLocation/ContentViewModel.swift
> +    internal func getPlaceName() -> String {
This version of getPlaceName() does not cause a compiler error.

2023-02-09 15:42 UTC, kittyTyree commented on SwiftUI-UserLocation/SwiftUI-UserLocation/ContentViewModel.swift
> +    internal func getPlaceName() -> String {
^ and by this version I mean the version that got changed

2023-02-09 23:45 UTC, Bottigerd commented on SwiftUI-UserLocation/SwiftUI-UserLocation/ContentViewModel.swift
> +    internal func getPlaceName() -> String {
I made getPlaceName() so that the given address when a place has a place ID is more helpful, otherwise its something like "Google Headquarters 6" or "118 Ellis St" and nothing else. I'll try to fix the compiler error so we can keep that helpful-ness. 

Do you know what coordinates you were using on your simulator when you got that error so I can recreate it?

2023-02-10 00:22 UTC, Bottigerd commented on SwiftUI-UserLocation/SwiftUI-UserLocation/ContentViewModel.swift
> +    internal func getPlaceName() -> String {
I split up the line that adds the different pieces of the place name and gave default values to the variables. I tried testing different locations to see if I could prompt the error again but I wasn't able to. So, either it's fixed or I still haven't found that edge case. Could you test again?

2023-02-10 00:41 UTC, alsheikha commented on SwiftUI-UserLocation/SwiftUI-UserLocation/ContentViewModel.swift
> +    internal func getPlaceName() -> String {
Your change worked for me! Gonna look at some of the other issues now

2023-02-10 03:31 UTC, kittyTyree approved these changes

2023-02-10 03:32 UTC, kittyTyree commented on SwiftUI-UserLocation/SwiftUI-UserLocation/ContentViewModel.swift
> +    internal func getPlaceName() -> String {
Worked no issues!

2023-02-10 06:38 UTC, alsheikha approved these changes
returnString solution worked for me. Address still doesn't update on each click

2023-02-10 06:39 UTC, merged