Home Inference and Core Data Integration
Bottigerd/location-app pull request #8
Opened 2023-02-12 00:11 UTC by jamesmarlin

Added home inference functionality. 

We now have a rough version of using inputed data to calculate where a user lives. This is done under the gethome() function in the Inference file. You will also see the inference being made on screen rather than just the terminal. If there is no data inputted to the csv, then this will not work. 

Fetch requests call coredata entities, which we then use to make inferences.

2023-02-12 03:03 UTC, Bottigerd requested changes
See my comment on `InferenceView.swift`

2023-02-12 03:03 UTC, Bottigerd commented on SwiftUI-UserLocation/SwiftUI-UserLocation/InferenceView.swift
> +        let address = "You most likely live in " +  keys[0]
I am unable to go to the inference tab with a clean build/pull of this branch.

When the data tab has no data, I get this error: 
`Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[NSArray0objectAtIndex:]: index 0 beyond bounds for empty NSArray'`

When the data tab has one data entry, I get this:
`Fatal error: Index out of range`, that is referencing this line.

2023-02-12 03:56 UTC, jayti-a commented on SwiftUI-UserLocation/SwiftUI-UserLocation/InferenceView.swift
> +        let address = "You most likely live in " +  keys[0]
Did you enter data in the data tab before going to inference?

2023-02-12 04:02 UTC, Bottigerd commented on SwiftUI-UserLocation/SwiftUI-UserLocation/InferenceView.swift
> +        let address = "You most likely live in " +  keys[0]
I tried without data and with data. Without data gave the first error, with data gave the second one. Both gave fatal errors

2023-02-12 04:36 UTC, alsheikha commented on SwiftUI-UserLocation/SwiftUI-UserLocation/InferenceView.swift
> +        let address = "You most likely live in " +  keys[0]
Same. I thought it might be my data formatting but I tried a bunch of different things. What did your data look like?

2023-02-12 23:43 UTC, Bottigerd requested changes
Thank you for fixing the fatal error! Does it take a certain number of entries to trigger the inference? I tried having ~5 entries on different days between 10pm and 6am, all at the same location (10, 10, 10 just for easy dataset purposes) and couldn't get the inference to trigger. How can I get it to work?

Also, main needs to be merged into the branch before the branch can then be merged into main. If this doesn't happen, the things that were merged between the start of this branch and now would be deleted.

2023-02-13 17:48 UTC, kevinpkw19 approved these changes
lgtm!

2023-02-13 17:57 UTC, kittyTyree commented
Works for me, guessed my home from the data I put in. Everything looks good.

2023-02-13 17:58 UTC, kittyTyree approved these changes

2023-02-15 00:41 UTC, Bottigerd approved these changes

2023-02-15 01:39 UTC, merged